CheckMate2017-master/checkmate2017/checkmate2017/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('mainapp.urls', namespace="mainapp")),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CheckMate2017-master/checkmate2017/mainapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^instructions$', views.instructions, name='instructions'),
    url(r'^game$', views.game, name='game'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^congrats$', views.congrats, name = 'congrats'),
    url(r'^logout$', views.logout, name = 'logout'),
    url(r'^question$',views.question,name='question'),
    url(r'^query$',views.query,name='query'),
    url(r'^pingme$',views.pingme,name='pingme'),
    url(r'^pingservers$',views.pingservers,name='pingservers'),
    url(r'^leaderboard$',views.leaderboard,name='leaderboard'),
]

CheckMate2017-master/checkmate2017/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
import re
from django.core import validators


class UserProfile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE) #extending user model
	teamname = models.CharField(max_length=200)
	idno1 = models.CharField(max_length=20,validators=[\
		validators.RegexValidator(re.compile('^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P$'),message='Enter your valid BITS-mail',code='invalid!')])
	idno2 = models.CharField(null=True,blank=False,max_length=20,validators=[\
		validators.RegexValidator(re.compile('^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P$'),message='Enter your valid BITS-mail',code='invalid!')])

	score = models.IntegerField(default=0)
	ip_address = models.CharField(null=True,max_length=20)
	status = models.CharField(max_length=80,default="00000000000000000000000000000000000000000000000000000")
	attempts= models.CharField(max_length=80,default="0000000000000000000000000000000000000000000000000000000")
	bstat = models.CharField(max_length=80,default="0000000000000000000000000000000000000000000000000000000")
	wrong_responses= models.IntegerField(default=0)
	logstat=models.IntegerField(null=False, choices=((0,'0'),(1,'1')),default=0)#0 for logged out, 1 for logged in
	sprite=models.CharField(null=False,max_length=50,choices=(('girl','girl'),('boy','boy')),default='Null')


	def __str__(self):
		return self.teamname

class Building(models.Model):
        building_name = models.CharField(max_length=100)
        q_total = models.IntegerField(default=1)

        def __str__(self):
                return self.building_name

class Question(models.Model):
        building_context = models.ForeignKey(Building,on_delete=models.CASCADE)
        points= models.IntegerField(null=False)
        question_text=RichTextField()
        difficulty_level=models.IntegerField(choices=((1,'1'),(2,'2'),(3,'3'),(4,'4'),(5,'5')),default=1)

        def __str__(self):
                return "Question #"+str(self.pk)

class Answer(models.Model):
		context = models.ForeignKey(Building, on_delete=models.CASCADE)
		answer = models.CharField(max_length=100,default='ah')

		def __str__(self):
			return "Answer @"+str(self.context)

class GameSwitch(models.Model):
		name=models.CharField(null=False,max_length=10)
		start_game = models.IntegerField(null=False, choices=((0,'0'),(1,'1')),default = 1)
		end_game = models.IntegerField(null=False, choices=((0,'0'),(1,'1')),default=0)#0 is switch status inactive, 1 is active

		def __str__(self):
				return self.name

class TeamProfile(models.Model):
	teamname = models.CharField(max_length=200)
	idno1 = models.CharField(max_length=20,primary_key=True, validators=[
		validators.RegexValidator(re.compile('^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P$'), message='Enter your valid BITS-mail', code='invalid!')])

	def __str__(self):
    		return self.teamname

CheckMate2017-master/checkmate2017/mainapp/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile
import re
from django.core import validators

class TeamForm(forms.Form):
	teamname1 = forms.CharField(max_length=50)
	password1 = forms.CharField(widget=forms.PasswordInput(),max_length=50)
	idno1 = forms.CharField(max_length=20,validators=[\
		validators.RegexValidator(re.compile('^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P'),message='BITS ID of teammate 1 is empty or invalid',code='invalid!')])
	idno2 = forms.CharField(required=False,max_length=20,validators=[\
		validators.RegexValidator(re.compile('^201[0-9]{1}[0-9A-Z]{4}[0-9]{4}P'),message='BITS ID of teammate 2 is empty or invalid',code='invalid!')])


class LoginForm(forms.Form):
        teamname=forms.CharField(max_length = 50)
        password=forms.CharField(widget=forms.PasswordInput())


class AnswerForm(forms.Form):
	answer=forms.CharField(required=True,max_length=100)
	pkvalue=forms.CharField(max_length=100)

CheckMate2017-master/checkmate2017/mainapp/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponse, Http404 ,HttpResponseForbidden
from .models import UserProfile, GameSwitch, Building, Question, Answer, TeamProfile
from django.shortcuts import redirect, render_to_response
from django.contrib.auth import authenticate, login, logout as django_logout
from django.contrib import auth
from .forms import TeamForm, LoginForm, AnswerForm
from django.db import IntegrityError
from django.contrib.auth.models import User
from .controls import calculate_score
from ipware.ip import get_ip
import json
from django.core import serializers
from django.contrib.auth.decorators import login_required
from .leaderboard import pingservers
import urllib, requests, sys
from django.views.decorators.csrf import csrf_exempt

def test(request):
    return HttpResponse('Fack! it is working :D')

def index(request):
    if not request.user.is_authenticated or request.user.username == "admin":
        return render(request, 'mainapp/index.html',)
    else:
        return redirect('mainapp:game')

def register(request):
    up = UserProfile.objects.filter(ip_address=get_ip)
    if up is None or 1:
        print("reached0")
        form = TeamForm(request.POST)
        if request.method == 'POST' :
            if form.is_valid():
                print (form)
                print("reached1")
                data = form.cleaned_data
                ###  Patch for Issue 2
                ###  TeamProfile object created here.
                team = TeamProfile()
                team.teamname = data['teamname1']
                team.idno1 = data['idno1']
                try:
                    t = TeamProfile.objects.get(pk=data['idno1'])
                    resp = {
                        'status': 'error',
                        'msg': 'BITS ID 1 has already been used to create a Team!  '
                    }
                    return HttpResponse(json.dumps(resp), content_type="application/json", status=500)
                except Exception:
                    team.save()
                ### Patch Ends
                u = User()
                u.username = data['teamname1']
                u.set_password(data['password1'])
                try:
                    u.save()
                except IntegrityError:
                    print("reached2")
                    resp={
                    'status': 'error',
                    'msg': 'Team name already registered or other conflicting entries'
                    }
                    return HttpResponse(json.dumps(resp), content_type = "application/json",status=500)
                
                up = UserProfile()
                up.user = u
                up.teamname = data['teamname1']
                up.idno1=data['idno1']
                up.idno2=data['idno2']
                up.ip_address = get_ip(request)
                up.save()
                #return redirect('mainapp:login')
                r={
                "status":"redirect",
                "url":"login"
                }
                print("reachedXXXX")
                return HttpResponse(json.dumps(r),content_type="application/json")
            else:
                error=json.loads(json.dumps(form.errors))
                error1=[]
                for e in error:
                    d=e
                    print("d",d)
                    if(d in ["password1","teamname1"]):
                        d=d[:-1]
                    error1.append(d)
                    error1.append('-')
                    error1.append((error[e])[0])
                    error1.append('<br/>')
                print(error1)
                resp={
                'status':'error',
                'msg':' '.join(error1)
                }
                print("reachedbbbbb")
                return HttpResponse(json.dumps(resp), content_type = "application/json",status=500)
        else:
            form=TeamForm(request.POST)
            r={
            "status":"redirect",
            "url":"login"
            }
            print("reached3")
            return HttpResponse(json.dumps(r),content_type="application/json",status=301)
    else:
        return HttpResponse('You have already registered once from this pc! Contact nearest ACM invigilator')


def instructions(request):
    return render(request, 'mainapp/instructions.html')

def login(request):
    if request.user.is_authenticated() and not request.user.username == "admin":
        return redirect('mainapp:game')
    else:
        g=GameSwitch.objects.get(name='main')
        if g.start_game:
            print("reachedl0")
            tform=TeamForm(request.POST)
            lform = LoginForm(request.POST)
            if request.method == 'POST':
                print("reachedl1")
                if lform.is_valid():
                    print("reachedl2")
                    data=lform.cleaned_data
                    teamname = data['teamname']
                    password = data['password']
                    user = authenticate(username = teamname, password=password)
                    if user is not None:
                        print("reachedl3")
                        auth.login(request, user)
                        return redirect(reverse('mainapp:game'))
                    else:
                        print("reachedl4")
                        resp={
                        'status':'error',
                        'msg':'Register before you try to Login!'
                        }
                        return HttpResponse(json.dumps(resp), content_type = "application/json",status=500)
                else:
                    error=json.loads(json.dumps(lform.errors))
                    error1=[]
                    for e in error:
                        d=e
                        print("d",d)
                        if(d in ["password1","teamname1"]):
                            d=d[:-1]
                        error1.append(d)
                        error1.append('-')
                        error1.append((error[e])[0])
                        error1.append('<br/>')
                    print(error1)
                    resp={
                    'status':'error',
                    'msg':' '.join(error1)
                    }
                    print("reachedbbbbb")
                    return HttpResponse(json.dumps(resp), content_type = "application/json",status=500)
            else:
                lform=LoginForm(request.POST)
                return render(request, 'mainapp/login.html',{'lform':lform,'tform':tform})
            return render(request, 'mainapp/login.html',{'lform':lform,'tform':tform})
        else:
            resp={
            'status':'error',
            'msg':'The game has not started yet',
            }
            return HttpResponse(json.dumps(resp), content_type = "application/json",status=500)

def phode_lite(request):
    if request.user.is_authenticated():
        up=UserProfile.objects.get(user=request.user)
        bs= list(up.bstat)
        k=0
        phoda=[]
        lite=[]
        for i in bs:
            k+=1
            if i == '1':
                phoda.append(Building.objects.get(pk=k).building_name)
            if i == '2':
                lite.append(Building.objects.get(pk=k).building_name)
        return [phoda, lite]


def game(request):
    if not (request.user).is_authenticated() or (request.user.username) == "admin":
        return redirect('mainapp:login')
    else:
        up = UserProfile.objects.get(user=request.user)
        switch=GameSwitch.objects.get(name='main')

        if up.logstat==1 and request.method=='GET':
            return redirect('mainapp:congrats')

        else:
            buildings = Building.objects.all()
            d={}
            if 'bquery' in request.POST:
                if switch.end_game==1:
                    up.logstat=1
                    resp={
                    'status':'error',
                    'msg':'Time up'
                    }
                    return HttpResponse(json.dumps(resp), content_type = "application/json",status=500)
                bquery = request.POST['bquery']
                bl = Building.objects.get(building_name=bquery)
                qs = Question.objects.filter(building_context=bl)
                for i in qs:
                    d[i.pk-1]=json.loads(serializers.serialize('json', [i,]))
                return HttpResponse(json.dumps(d), content_type = "application/json")
            [phoda, lite] = phode_lite(request)
            return render(request, 'mainapp/game.html',{'up':up,'buildings':buildings,"phoda": phoda, "lite": lite})

def question(request):
        up = UserProfile.objects.get(user=request.user)
        sl= list(up.status)
        at= list(up.attempts)
        bs= list(up.bstat)
        ansform=AnswerForm(request.POST)

        if request.method == 'POST' and 'pkvalue' in request.POST:

            if ansform.is_valid():
                ques_id=request.POST['pkvalue']
                index = int(ques_id)-1
                q = Question.objects.get(pk=ques_id)
                a= Answer.objects.get(context=(Building.objects.get(building_name=q.building_context)))
                data=ansform.cleaned_data
                ans= data['answer']
                qs=Question.objects.all()
                resp={}

                if ans is not None:
                    if sl[index]=="1":
                        resp={
                        'status':'error',
                        'msg':"Already attempted this question correctly!"
                        }
                        return HttpResponse(json.dumps(resp), content_type = "application/json",status=500)
                    elif int(at[index])>=3 and sl[index]=="0":
                        resp={
                        'status':'error',
                        'msg':"Maximum attempts reached"
                        }

CheckMate2017-master/checkmate2017/mainapp/templates/mainapp/congrats.html
<!DOCTYPE html>
{%load static from staticfiles%}
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Congrats</title>
      <link rel="stylesheet" type="text/css" href="{% static 'mainapp/fonts/fonts.css'%}">
      <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/congrats.css' %}">

   </head>

   <body>
     <!-- <div class="card" id="main">
        <div class="top">
            <h1>Congratulations!</h1>
            <h3>You have successfully completed the game !</h3>
            <div class="check">
              Checkmate
            </div>
        </div>
        <div class="bottom">
            <a href="{% url 'mainapp:logout' %}">LOG OUT</a>
        </div>
      </div> -->
        <div id="footer"></div>
      <div id="wrapper">
        <div class="main">
          <div class="box">
            <span>Your score: {{a}}</span>

          </div>
          <div class="box"><a href="/logout">Logout</a></div>
        </div>
      </div>
      <script>
      var a = {{a}};
      </script>

   </body>
</html>

CheckMate2017-master/checkmate2017/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html lang="en" class="no-js">
{% load static %}
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Checkmate</title>
		<link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/normalize.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/main.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/style.css' %}"/>
		<!-- <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'> -->
		<link rel="stylesheet" type="text/css" href="{% static 'mainapp/fonts/fonts.css' %}"/>
		<script src="{% static 'mainapp/js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'mainapp/js/main1.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/loader.css' %}">
		<script type="text/javascript">
			function loadRem(){
				document.getElementById("loader-wrapper").style.display="none";
				document.getElementById("entire").style.display="block";
			}
		</script>
	</head>
	<body onload="loadRem()" style="background: url('./media/img/back1.jpg') no-repeat; background-size:cover;">
		<div id="loader-wrapper">
			<div id="loader"></div>

			<div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>

		</div>
		<div id="entire">


			<div  class="open">
					<span class="cls"></span>
					<span>
							<ul class="sub-menu ">
									<li>
											<a href="{% url 'mainapp:index' %}" title="home">Home</a>
									</li>
									<li>
											<a href="{% url 'mainapp:instructions' %}" title="instr">Instructions</a>
									</li>
									<!-- <li>
											<a href="{% url 'mainapp:leaderboard' %}" title="lead">Leaderboard</a>
									</li> -->
									<li>
											<a href="{% url 'mainapp:login' %}" title="regis">Login</a>
									</li>
							</ul>
					</span>
					<span class="cls"></span>
			</div>


		<div id="header">
			<h1>Checkmate</h1>
		</div>
		<div class="container">
			<div class="content">
				<section class="section" style="margin-top:150px;">
					<svg xmlns="http://www.w3.org/2000/svg" version="1.1" class="svg-filters">
						<defs>
							<filter id="filter-glitch-1">
								<feTurbulence type="fractalNoise" baseFrequency="0.000001" numOctaves="1" result="warp" />
								<feOffset dx="-90" dy="-90" result="warpOffset" />
								<feDisplacementMap xChannelSelector="R" yChannelSelector="G" scale="30" in="SourceGraphic" in2="warpOffset" />
							</filter>
						</defs>
					</svg>
					<a href = "{% url 'mainapp:game' %}"><button id="component-5" class="button button--5" >Start</button><a/>
				</section>

			</div>
		</div>
	</div>
		<script src="{% static 'mainapp/js/TweenMax.min.js' %}"></script>
		<script src="{% static 'mainapp/js/main.js' %}"></script>
	</body>
</html>

CheckMate2017-master/checkmate2017/mainapp/templates/mainapp/instructions.html
{%load static from staticfiles%}

<!Doctype html>
<html lang="en">
<head>
<meta name="viewport" content="width = 1050,user-scalable = no " />
<link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/basic.css' %}" />
<script type="text/javascript" src="{% static 'mainapp/extras/jquery.min.1.7.js' %}"></script>
<script type="text/javascript" src="{% static 'mainapp/extras/modernizr.2.5.3.min.js' %}"></script>
</head>
<body>
	<div  class="open">
			<span class="cls"></span>
			<span>
					<ul class="sub-menu ">
									<li>
											<a href="{% url 'mainapp:index' %}" title="home">Home</a>
									</li>
									<li>
											<a href="{% url 'mainapp:instructions' %}" title="instr">Instructions</a>
									</li>
									<!-- <li>
											<a href="#" title="lead">Leaderboard</a>
									</li> -->
									<li>
											<a href="{%  url 'mainapp:login' %}" title="regis">Login</a>
									</li>

					</ul>
			</span>
			<span class="cls"></span>
	</div>

<div class="flipbook-viewport">
	<div class="container">
		<div class="flipbook">
			<div style="background-image:url( {% static 'mainapp/img/pages/page0.png' %} )"></div>
			<div style="background-image:url( {% static 'mainapp/img/pages/page1.png' %} )"></div>
			<div style="background-image:url( {% static 'mainapp/img/pages/page2.png' %} )"></div>
			<div style="background-image:url( {% static 'mainapp/img/pages/page3.png' %} )"></div>
			<!-- <div style="background-image:url( {% static 'mainapp/img/pages/2.jpg' %} )"></div>
			<div style="background-image:url( {% static 'mainapp/img/pages/4.jpg' %} )"></div>
			<div style="background-image:url( {% static 'mainapp/img/pages/2.jpg' %} )"></div> -->
		</div>
	</div>
</div>


<script type="text/javascript">

function loadApp() {

	$('.flipbook').turn({
			// Width

			width:800,

			// Height

			height:500,

			// Elevation

			elevation: 50,

			// Enable gradients

			gradients: true,

			// Auto center this flipbook

			autoCenter: true

	});
}

yepnope({
	test : Modernizr.csstransforms,
	yep: ['{% static 'mainapp/lib/turn.js' %}'],
	nope: ['{% static 'mainapp/lib/turn.html4.min.js' %}'],
	both: ['{% static 'mainapp/css/basic.css' %} '],
	complete: loadApp
});

</script>
<script type ="text/javascript" src="{% static 'mainapp/js/main.js' %}"></script>
</body>
</html>

CheckMate2017-master/checkmate2017/mainapp/templates/mainapp/leaderboard.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'mainapp/js/Update.js' %}"></script>
    </head>
    <body>
        <input type="button" onclick="UpdateList()" value="Update Rank List"/>
        <div id="leaderboard">
            <ol id="results">
            </ol>
        </div>
    </body>
</html>

CheckMate2017-master/checkmate2017/mainapp/templates/mainapp/login.html
<!DOCTYPE html>
<html lang="en" class="no-js">
{% load static from staticfiles %}
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{% static 'mainapp/css/login.css' %}">
		<link rel="stylesheet" href="{% static 'mainapp/css/style.css' %}">
		<script src="{% static 'mainapp/js/jquery.min.js' %}"></script>
		  </head>

	<body>
		<div  class="open">
				<span class="cls"></span>
				<span>
						<ul class="sub-menu ">
									<li>
											<a href="{% url 'mainapp:index' %}" title="home">Home</a>
									</li>
									<li>
											<a href="{% url 'mainapp:instructions' %}" title="instr">Instructions</a>
									</li>
									<!-- <li>
											<a href="#" title="lead">Leaderboard</a>
									</li> -->
									<li>
											<a href="{% url 'mainapp:login' %}" title="regis">Login</a>
									</li>
							</ul>
				</span>
				<span class="cls"></span>
		</div>


		<div class="panel">
		  <ul class="panel__menu" id="menu">
		    <hr/>
		    <li id="signIn"> <a href="#">Log In</a></li>
		    <li id="signUp"><a href="#">&emsp;Sign up</a></li>
		  </ul>


		  <div class="panel__wrap">
		    <div class="panel__box active" id="signInBox">
		  <form id="login-form" action="{% url 'mainapp:login' %}" role="form" style="display: block;" method="POST" >
                {% csrf_token %}

                {% if error_message %}
                  {{ error_message }}
                {% endif %}

		      <label>Team name
		        <input data-check="teamname"  type="text" name="teamname" id="teamname" placeholder="Teamname" value="" >
		      </label>
		      <label>Password
		        <input type="password" name="password" id="password" placeholder="Password">
		      </label>
		      <input type="submit" name="login-submit" value="login"/>
		</form>
		    </div>



		    <div class="panel__box" id="signUpBox">
			<form id = "register-form" action ="{% url 'mainapp:register' %}" role="form" style="display: block;" method="POST" >
			{% csrf_token %}

                {% if error_message %}
                  {{ error_message }}
                {% endif %}
				      <label>Team name
		        <input  type="text" name="teamname1" id="team"    placeholder="Teamname">
		      </label>
			  <label>BITS ID1
		        <input  type="text" name="idno1" id='id1'   placeholder="BITS ID number">
		      </label>
		      <label>BITS ID2
		        <input  type="text" name="idno2" id='id2'    placeholder="BITS ID number(optional)">
		      </label>
		      <label>Password
		        <input type="password" name="password1" id='pass' placeholder="Password" >
		      </label>
					<input type="submit" name= "register-submit" value="Register Now"/>
			</form>
		    </div>
		  </div>
		  </div>


			<div id="msg_box"></div>
		<script>



			$("#register-form").submit(function(event){
					event.stopPropagation();
    			event.preventDefault();
					var datas={
						teamname1 : $('#team').val(),
						idno1 : $('#id1').val(),
						idno2 : $('#id2').val(),
						password1 : $('#pass').val(),
						csrfmiddlewaretoken: document.cookie.split("=")[1]
					}
					console.log(datas);
					var options = {
        	success:       showResponse,  // post-submit callback
					error: showError,
					data: datas,
        	url:       '/register',         // override for form's 'action' attribute
        	type:      'POST',        // 'get' or 'post', override for form's 'method' attribute
    	};
			$.ajax(options);
			return false;
		});


		$("#login-form").submit(function(event){
				event.stopPropagation();
				event.preventDefault();
				var datas={
					teamname : $('#teamname').val(),
					password : $('#password').val(),
					csrfmiddlewaretoken: document.cookie.split("=")[1]
				}
				console.log(datas);
				var options = {
				success:       showRes,  // post-submit callback
				error: showErr,
				data: datas,
				url:       '/login',         // override for form's 'action' attribute
				type:      'POST',        // 'get' or 'post', override for form's 'method' attribute
		};
		$.ajax(options);
		return false;
	});

			function showResponse(msg) {
				msgb("Successfully Registered In")
				window.location='/login';
				console.log(msg)
			}
			function showError(msg){
				console.log(msg);
				var errors=JSON.parse(msg['responseText']);
				msgb(errors.msg)
			}

			function showRes(msg) {
							msgb("Successfully Logged In")
							window.location='/game';
							console.log(msg)
						}
			function showErr(msg){
							console.log(msg);
							var errors=JSON.parse(msg['responseText']);
							msgb(errors.msg)
				}

				function msgb(string){
					console.log('msgb called')
					$("#msg_box").html(string);
					$("#msg_box").fadeIn();
					setTimeout(function(){
						$("#msg_box").fadeOut();
					}, 2000)
				}

		</script>

		<script src="{% static 'mainapp/js/login.js' %}"></script>
		<script src="{% static 'mainapp/js/main.js' %}"></script>
	</body>